### ISSUE TITLE
format of XZ file

### ISSUE THREAD

**Issue by hypadr1v3** [koomas/NDT_ML_Flaw#1]
Hi,
I tried to use this dataset but I can't seem to understand the format that this XZ file is stored as. I decompressed it and it gives me a huge (6.6gb) blob for each xz file that doesn't seem to have any set format. Is it a JPG file or some other format? If it is some type of custom format then could you please give an example on how to use it?

**Comment by koomas** [comment]
Each .xz and .lzma file are a set of 3D arrays. So you should use LZMA package within your python script to unpack these packed files and it should leave you with 1000x480x7168 3D array where x,y,z represent x image number, y width of the image and z the height of the image. This packed data contains only the images! The txt file with corresponding name contains metadata of the image such as flaw/no flaw and flaw location info.
